openapi: 3.0.0
info:
  title: OpenWeatherMap API
  description: 'Get the current weather, daily forecast for 16 days, and a three-hour-interval
    forecast for 5 days for your city. Helpful stats, graphics, and this day in history
    charts are available for your reference. Interactive maps show precipitation,
    clouds, pressure, wind around your location stations. Data is available in JSON,
    XML, or HTML format. **Note**: This sample Swagger file covers the `current` endpoint
    only from the OpenWeatherMap API. <br/><br/> **Note**: All parameters are optional,
    but you must select at least one parameter. Calling the API by city ID (using
    the `id` parameter) will provide the most precise location results. This is an
    update.'
  termsOfService: https://openweathermap.org/terms
  contact:
    name: Support
    url: https://openweathermap.org/api
    email: some_email@gmail.com
  license:
    name: CC Attribution-ShareAlike 4.0 (CC BY-SA 4.0)
    url: https://openweathermap.org/price
  version: "2.5"
servers:
- url: https://api.openweathermap.org/data/2.5
  description: prod
paths:
  /weather:
    get:
      tags:
      - Weather endpoints
      summary: weather
      description: Access current weather data for any location on Earth including
        over 200,000 cities! Current weather is frequently updated based on global
        models and data from more than 40,000 weather stations.
      operationId: get-weather
      parameters:
      - name: zip
        in: query
        description: '**Zip code**. Search by zip code. *Example: 95050,us*. Please
          note that if the country is not specified, the search uses USA as a default.'
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: units
        in: query
        description: '**Units**. *Example: imperial*. Possible values: `standard`,
          `metric`, and `imperial`. When you do not use the `units` parameter, the
          format is `standard` by default.'
        required: false
        style: form
        explode: false
        schema:
          type: string
          example: imperial
          default: standard
          enum:
          - standard
          - metric
          - imperial
      - name: q
        in: query
        description: '**City name**. *Example: London*. You can call by city name,
          or by city name and country code. The API responds with a list of results
          that match a searching word. For the query value, type the city name and
          optionally the country code divided by a comma; use ISO 3166 country codes.'
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: id
        in: query
        description: '**City ID**. *Example: `2172797`*. You can call by city ID.
          The API responds with the exact result. The List of city IDs can be downloaded
          [here](http://bulk.openweathermap.org/sample/). You can include multiple
          cities in this parameter — just separate them by commas. The limit of locations
          is 20. *Note: A single ID counts as a one API call. So, if you have city
          IDs, it’s treated as 3 API calls.*'
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: '''2172797'''
      - name: lat
        in: query
        description: '**Latitude**. *Example: 35*. The latitude coordinate of the
          location of your interest. Must use with `lon`.'
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: lon
        in: query
        description: '**Longitude**. *Example: 139*. Longitude coordinate of the location
          of your interest. Must use with `lat`.'
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: lang
        in: query
        description: '**Language**. *Example: en*. You can use lang parameter to get
          the output in your language. We support the following languages that you
          can use with the corresponded lang values: Arabic - `ar`, Bulgarian - `bg`,
          Catalan - `ca`, Czech - `cz`, German - `de`, Greek - `el`, English - `en`,
          Persian (Farsi) - `fa`, Finnish - `fi`, French - `fr`, Galician - `gl`,
          Croatian - `hr`, Hungarian - `hu`, Italian - `it`, Japanese - `ja`, Korean
          - `kr`, Latvian - `la`, Lithuanian - `lt`, Macedonian - `mk`, Dutch - `nl`,
          Polish - `pl`, Portuguese - `pt`, Romanian - `ro`, Russian - `ru`, Swedish
          - `se`, Slovak - `sk`, Slovenian - `sl`, Spanish - `es`, Turkish - `tr`,
          Ukrainian - `ua`, Vietnamese - `vi`, Chinese Simplified - `zh_cn`, Chinese
          Traditional - `zh_tw`.'
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: en
      - name: mode
        in: query
        description: '**Mode*. *Example: html. Determines the format of the response.
          Possible values are `json`, `xml`, and `html`. If the mode parameter is
          empty, the format is `json` by default.'
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: html
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
              examples:
                Example:
                  value:
                    coord:
                      lon: -121.95
                      lat: 37.35
                    weather:
                    - id: 803
                      main: Clouds
                      description: broken clouds
                      icon: 04n
                    base: stations
                    main:
                      temp: 45.25
                      feels_like: 41.16
                      temp_min: 41
                      temp_max: 50
                      pressure: 1026
                      humidity: 75
                    visibility: 16093
                    wind:
                      speed: 2.57
                      deg: 36
                    clouds:
                      all: 75
                    dt: 1579415808
                    sys:
                      type: 1
                      id: 5845
                      country: US
                      sunrise: 1579360793
                      sunset: 1579396557
                    timezone: -28800
                    id: 0
                    name: Santa Clara
                    cod: 200
            application/xml:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized_response'
      security:
      - app_id: []
      x-swagger-router-controller: WeatherEndpoints
components:
  schemas:
    unauthorized_response:
      title: "401"
      required:
      - cod
      - message
      type: object
      properties:
        cod:
          type: integer
        message:
          type: string
      description: Unauthorized
      x-examples: {}
    inline_response_200:
      type: object
      properties:
        coord:
          $ref: '#/components/schemas/inline_response_200_coord'
        cod:
          type: number
          description: Internal parameter
          example: 200
        name:
          type: string
          description: Name
          example: Cairns
        id:
          type: number
          description: City ID
          example: 2172797
        timezone:
          type: number
          description: the timezone for the station
          example: -28800
        sys:
          $ref: '#/components/schemas/inline_response_200_sys'
        dt:
          type: number
          description: ‘Time of data calculation, unix, UTC’
          example: 1435658272
        clouds:
          $ref: '#/components/schemas/inline_response_200_clouds'
        wind:
          $ref: '#/components/schemas/inline_response_200_wind'
        visibility:
          type: number
          description: ‘Visibility, meter’
          example: 16093
        main:
          $ref: '#/components/schemas/inline_response_200_main'
        base:
          type: string
          description: Internal parameter
          example: cmc stations
        weather:
          type: array
          items:
            $ref: '#/components/schemas/inline_response_200_weather'
      example:
        visibility: 16093
        timezone: -28800
        main:
          temp: 29325
          temp_min: 289.82
          humidity: 83
          pressure: 83
          feels_like: 41.16
          temp_max: 295.37
        clouds:
          all: 51
        sys:
          country: AU
          sunrise: 1435610796
          sunset: 1435650870
          id: 1
          type: 1
        dt: 1435658272
        coord:
          lon: 145.77
          lat: -16.92
        name: Cairns
        weather:
        - icon: 04n
          description: broken clouds
          main: clouds
          id: 0.80082819046101150206595775671303272247314453125
        - icon: 04n
          description: broken clouds
          main: clouds
          id: 0.80082819046101150206595775671303272247314453125
        cod: 200
        id: 2172797
        wind:
          deg: 150
          speed: 5.1
        base: cmc stations
    inline_response_200_1:
      type: object
      properties:
        ? ""
        : type: string
    inline_response_200_coord:
      type: object
      properties:
        lon:
          type: number
          description: City geo location, longitude
          example: 145.77
        lat:
          type: number
          description: City geo location, latitude
          example: -16.92
      example:
        lon: 145.77
        lat: -16.92
    inline_response_200_sys:
      type: object
      properties:
        type:
          type: number
          description: Internal parameter
          example: 1
        id:
          type: number
          description: Internal parameter
          example: 1
        country:
          type: string
          description: ‘Country code (GB, JP etc.)’
          example: AU
        sunrise:
          type: number
          description: ‘Sunrise time, unix, UTC’
          example: 1435610796
        sunset:
          type: number
          description: ‘Sunset time, unix, UTC’
          example: 1435650870
      example:
        country: AU
        sunrise: 1435610796
        sunset: 1435650870
        id: 1
        type: 1
    inline_response_200_clouds:
      type: object
      properties:
        all:
          type: number
          description: ‘Cloudiness, %’
          example: 51
      example:
        all: 51
    inline_response_200_wind:
      type: object
      properties:
        speed:
          type: number
          description: '‘Wind speed. Unit Default: meter/sec, Metric: meter/sec, Imperial:
            miles/hour.’'
          example: 5.1
        deg:
          type: number
          description: ‘Wind direction, degrees (meteorological)’
          example: 150
      example:
        deg: 150
        speed: 5.1
    inline_response_200_main:
      required:
      - temp_max
      type: object
      properties:
        temp:
          type: number
          description: '‘Temperature. Unit Default: Kelvin, Metric: Celsius, Imperial:
            Fahrenheit.’'
          example: 29325
        feels_like:
          type: number
          description: What the weather feels like despite the actual numbers
          example: 41.16
        temp_min:
          type: number
          description: '‘Minimum temperature at the moment. This is deviation from
            current temp that is possible for large cities and megalopolises geographically
            expanded (use these parameter optionally). Unit Default: Kelvin, Metric:
            Celsius, Imperial: Fahrenheit.’'
          example: 289.82
        temp_max:
          type: number
          description: '‘Maximum temperature at the moment. This is deviation from
            current temp that is possible for large cities and megalopolises geographically
            expanded (use these parameter optionally). Unit Default: Kelvin, Metric:
            Celsius, Imperial: Fahrenheit.’'
          example: 295.37
        pressure:
          type: number
          description: ‘Atmospheric pressure (on the sea level, if there is no sea_level
            or grnd_level data), hPa’
          example: 83
        humidity:
          type: number
          description: ‘Humidity, %’
          example: 83
      example:
        temp: 29325
        temp_min: 289.82
        humidity: 83
        pressure: 83
        feels_like: 41.16
        temp_max: 295.37
    inline_response_200_weather:
      type: object
      properties:
        id:
          type: number
          description: Weather condition id
        main:
          type: string
          description: ‘Group of weather parameters (Rain, Snow, Extreme etc.)’
          example: clouds
        description:
          type: string
          description: Weather condition within the group
          example: broken clouds
        icon:
          type: string
          description: Weather icon id
          example: 04n
      example:
        icon: 04n
        description: broken clouds
        main: clouds
        id: 0.80082819046101150206595775671303272247314453125
  parameters:
    lon:
      name: lon
      in: query
      description: '**Longitude**. *Example: 139*. Longitude coordinate of the location
        of your interest. Must use with `lat`.'
      required: false
      style: form
      explode: true
      schema:
        type: string
  securitySchemes:
    app_id:
      type: apiKey
      name: appid
      in: query
